name: Build Cloudflared

on:
  workflow_dispatch:    # 允许手动触发工作流
  push:
    branches: [ main ]  # 推送到 main 分支时触发
  pull_request:
    branches: [ main ]  # 针对 main 分支创建 PR 时触发
  release:
    types: [created]    # 创建 Release 时触发

jobs:
  build-cloudflared:
    name: Build cloudflared - ${{ matrix.target_os }} ${{ matrix.target_arch }}
    runs-on: ubuntu-latest  # 使用 GitHub 托管的 Ubuntu 运行器
    strategy:
      matrix:
        include:
          - target_arch: arm64
            target_os: linux
            artifact_name: cloudflared-linux-arm64
    # 设置环境变量，方便后续步骤引用
    env:
      TARGET_ARCH: ${{ matrix.target_arch }}
      TARGET_OS: ${{ matrix.target_os }}
      ARTIFACT_NAME: ${{ matrix.artifact_name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment for ARM64 build
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Run make command
      run: make cloudflared TARGET_ARCH=$TARGET_ARCH TARGET_OS=$TARGET_OS
      env:
        CC: aarch64-linux-gnu-gcc
        CXX: aarch64-linux-gnu-g++

    - name: List output files (for debugging)
      run: ls -la

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: cloudflared           # 上传 make 生成的名为 'cloudflared' 的二进制文件
        if-no-files-found: error    # 如果未找到文件则失败
